### ISSUE TITLE
Android 4.4 - setsockopt SO_REUSEPORT: Protocol not available

### ISSUE THREAD

**Issue by ewwink** [pcherenkov/udpxy#10]
It running find on Android 6 but I got this error when running on Android 4.4

```
# udpxy -vT -a wlan0 -m eth0 -p 8888
Added client: pid=[17586], maddr=[239.1.1.15], mport=[8064], saddr=[192.168.100.2], sport=[26015]
setup_mcast_listener: setsockopt SO_REUSEPORT: Protocol not available
```

**Comment by pcherenkov** [comment]
Ah.. too bad I don't have Android (of any version) set up to test and figure it out. Third-party patches are welcome for this one.

**Comment by pcherenkov** [comment]
I am expiring this issue, no takers.
