### ISSUE TITLE
gcc9 warns about s_sysinfo size

### ISSUE THREAD

**Issue by timp87** [pcherenkov/udpxy#13]
This problem appears again:
```
util.c: In function 'get_sysinfo':
util.c:1082:61: error: ' ' directive output may be truncated writing 1 byte into a region of size between 0 and 255 [-Werror=format-truncation=]
 1082 |         (void) snprintf (s_sysinfo, sizeof(s_sysinfo)-1, "%s %s %s",
      |                                                             ^
util.c:1082:16: note: 'snprintf' output between 3 and 768 bytes into a destination of size 255
 1082 |         (void) snprintf (s_sysinfo, sizeof(s_sysinfo)-1, "%s %s %s",
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1083 |             uts.sysname, uts.release, uts.machine);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
s_sysinfo was extended to 256 before in https://github.com/pcherenkov/udpxy/commit/2cdb00f6198b0dd2be7b164a4e9a897adc57ce55, but this is not enough for gcc9.

I suppose this should be reworked somehow.

Also seems like snprintf() always null terminates the buffer. Is such code really needed?
https://github.com/pcherenkov/udpxy/blob/master/chipmunk/util.c#L1081

**Comment by pcherenkov** [comment]
What distro/repo are you using that that has gcc-9?

**Comment by timp87** [comment]
Oh, sorry. This is Freebsd 12.1

**Comment by pcherenkov** [comment]
I just pushed out the new *sysinfo-gcc9* branch w/o testing on gcc9, please try it out and let me know if it works. s_sysinfo is extended to 1024, snprintf() taken care of, too.

**Comment by timp87** [comment]
It compiled and seems working

**Comment by pcherenkov** [comment]
ok then

**Comment by timp87** [comment]
let's close this issue
