### ISSUE TITLE
clang compilation: pointer-bool-conversion warning

### ISSUE THREAD

**Issue by timp87** [pcherenkov/udpxy#14]
I want to update FreeBSD net/udpxy port to the latest version.
Under FreeBSD 12.1 with clang 8 from base system I get this:
```
cc -W -Wall -Werror --pedantic -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing   -DUDPXREC_MOD -DNDEBUG -DTRACE_MODULE -c mkpg.c -o mkpg.o

mkpg.c:93:29: error: address of array 'client->tail' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
                    client->tail ? client->tail : "",
                    ~~~~~~~~^~~~ ~
mkpg.c:100:25: error: address of array 'client->tail' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
            if (client->tail && (ssize_t)strlen(client->tail) > max_cli_tail)
                ~~~~~~~~^~~~ ~~
2 errors generated.
```
The same error with clang 9.

**Comment by pcherenkov** [comment]
Yeah, obviously a bug, long overlooked. Stand by for a fix.

**Comment by pcherenkov** [comment]
Branch ctail-fix has the fix, please try it.

**Comment by timp87** [comment]
It works, thanks!

**Comment by timp87** [comment]
Will you include this into udpxy-1.0.24.2?

**Comment by pcherenkov** [comment]
I'll bundle it into .1, enough for 1 patch.

**Comment by pcherenkov** [comment]
Merged & pushed.

**Comment by timp87** [comment]
Well, could you please describe how to track udpxy versions then?
There is no git tag in this repo.
There is no versioning in http://www.udpxy.com/download/udpxy/ too.
How can I refer to udpxy-1.0.24.1 _release_ then?

**Comment by pcherenkov** [comment]
Pushed out 1.0-24.1 tag.

**Comment by timp87** [comment]
Thanks a lot!
Please close this issue.
