### ISSUE TITLE
IPv6 Support?

### ISSUE THREAD

**Issue by jdjingdian** [pcherenkov/udpxy#17]
Hi! Appreciate for your great work.
I would like to know if there is a way to make udpxy listen both on ipv4&&ipv6 request?

**Comment by pcherenkov** [comment]
IPv6 support isn't there simply due to the lack of demand. The previous
request to add it was almost 10 years ago, so I added IPv6 support to
Gigapxy. No plans to add it to udpxy at the time (IPv6 is still unpopular).

**Comment by rozhuk-im** [comment]
> Hi! Appreciate for your great work.
> I would like to know if there is a way to make udpxy listen both on ipv4&&ipv6 request?

Try https://github.com/rozhuk-im/msd_lite
