### ISSUE TITLE
udpxy and ssm

### ISSUE THREAD

**Issue by hackruu** [pcherenkov/udpxy#2]
Hello!
I wonder, will be ssm/imr supported in udpxy someday? Last time i saw this was asked, it was 2012, maybe something changed in roadmap.

**Comment by OmegaVVeapon** [comment]
I added SSM on a fork from udpxy. It works well. I'll get off my butt and submit a PR someone this month

**Comment by OmegaVVeapon** [comment]
Submitted PR #6

**Comment by pcherenkov** [comment]
> Submitted PR #6

Thank you, it's a big change and quite useful. I feel that your branch should be used by those needing SSM.

**Comment by pcherenkov** [comment]
I think it ends this issue (please use the branch by OmegaVVeapon).
