### ISSUE TITLE
IGMP V3 SSM support

### ISSUE THREAD

**Issue by lstankiewicz** [pcherenkov/udpxy#20]
Hello, 
This is rather feature request than a bug.
Multiple providers deliver their multicast as IGMP v3 SSM (source specific multicast) for example: 
rtp://192.168.10.25@232.10.16.25:10000 
and that can't be relayed by udpxy at all. 
Those SSM multicasts are causing "issues" as many of the software just don't support those at all, tvheadend for example, but support http streams without issue.
There are workarounds by using ffmpeg to translate ssm multicast to fifio pipe but those are CPU intensive.
Having udpxy be able to convert ssm to http stream would be quite nice.

**Comment by pcherenkov** [comment]
It's done. Just merged in a pull request with SSM. 1.0-25.0 has it now.
