### ISSUE TITLE
status page

### ISSUE THREAD

**Issue by dzanob** [pcherenkov/udpxy#7]
Hello,
please, is there a way to block status html page? 

Thank You

**Comment by barhom** [comment]
Yes there is a way with iptables, I dont remember exactly but it should be quite easy.

**Comment by javiermatos** [comment]
An easy way to block or secure udpxy is to use it behind nginx and enforce basic authentication.

**Comment by pcherenkov** [comment]
I understand your concern but security, authentication, etc. falls into the enterprise-feature bucket. That bucket I don't fill for udpxy, sorry. Go Gigapxy if you will. Cheers.
